const FlowTypes = {
  FETCH_IMPAIRED_DATA: 'FETCH_IMPAIRED_DATA',
  FETCH_UNIMPAIRED_DATA: 'FETCH_UNIMPAIRED_DATA',
  FETCH_IMPAIRED_AGGR_DATA: 'FETCH_IMPAIRED_AGGR_DATA',
  FETCH_UNIMPAIRED_AGGR_DATA: 'FETCH_UNIMPAIRED_AGGR_DATA',
  UPDATE_CURRENT_FLOW_DATA: 'UPDATE_CURRENT_FLOW_DATA',
};

export default FlowTypes;
